### ISSUE TITLE
Character Content not recognized by ICDAR 2015 pre-trained model

### ISSUE THREAD

**Issue by ShaheenPerveen** [mjq11302010044/RRPN_plusplus#10]
I am using the pre-trained model for testing on my own images. I had downloaded model_IC15_89.pth using the link https://drive.google.com/file/d/1nv-ZjbYBj8ePZRa_fAhbHvzm7HqSxPWK/view?usp=sharing and changed the path to the location of this checkpoint in configs/arpn_E2E/e2e_rrpn_R_50_C4_1x_test_AFPN_RT_LERB_Spotter.yaml
The output generated by the pretrained model looks like this
```
270,558,331,487,347,500,287,572
236,534,286,479,300,492,251,547
285,570,343,499,358,511,300,583
398,471,441,420,456,433,413,483
394,320,448,256,461,268,407,331
...
```
I am assuming the detection head of the model is working and hence it is able to detect some of the words in the image and provide the coordinates as output but the recognition head is not able to recognize the character content of the boxes detected by detection head.

@mjq11302010044 Could you please help me with understanding why the implementation is not able to recognise any character?

**Comment by kbrajwani** [comment]
Hey @ShaheenPerveen  can you please tell me how you run this project on own image. i have done setup but i am facing this issue.
**We don't expect you to use default class number...Retry it**
**Empty alphabet...**
Traceback (most recent call last):
  File "demo/rrpn_e2e_infer.py", line 38, in <module>
    confidence_threshold=0.1,
  File "/content/RRPN_plusplus/demo/predictor.py", line 653, in __init__
    self.model.to(self.device)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/usr/local/lib/python3.7/dist-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

I have changed the path of model in config yml file.

**Comment by mjq11302010044** [comment]
@kbrajwani The problem may be the lack of alphabet file. We have updated the necessary alphabet for your testing. If you have any further problems please feel free to leave message.

**Comment by kbrajwani** [comment]
@mjq11302010044  Thanks

**Comment by kbrajwani** [comment]
![image](https://user-images.githubusercontent.com/29722986/117179334-a6600900-adf0-11eb-85a1-d231a2fd412c.png)
Hey can you help me here?
