### ISSUE TITLE
error in demo

### ISSUE THREAD

**Issue by ljcljc** [mjq11302010044/RRPN_plusplus#13]
I tried to run "demo/rrpn_e2e_infer.py", but it shows error. Does anyone know the reason?

I just want to test the result using a pre-trained model, did I do anything wrong? Thanks.

  warnings.warn(WRONG_COMPILER_WARNING.format( 
Traceback (most recent call last):
  File "/root/rrpn/RRPN_plusplus/demo/rrpn_e2e_infer.py", line 11, in <module>
    from demo.predictor import ICDARDemo, RRPNDemo
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/demo/predictor.py",
 line 6, in <module>
    from maskrcnn_benchmark.modeling.detector import build_detection_model
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/
modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/
modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/
modeling/detector/generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/
modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/modeling/backbone/backbone.py", line 7, in <module>
    from maskrcnn_benchmark.modeling.make_layers import conv_with_kaiming_uniform
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/modeling/make_layers.py", line 10, in <module> 
    from maskrcnn_benchmark.layers import Conv2d
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/layers/__init__.py", line 8, in <module>
    from .roi_align import ROIAlign
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/layers/roi_align.py", line 9, in <module>
    from ._utils import _C
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/layers/_utils.py", line 39, in <module>
    _C = _load_C_extensions()
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/layers/_utils.py", line 31, in _load_C_extensions
    return load_ext(
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1337, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1436, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1875, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1926, in _write_ninja_file
    assert len(sources) > 0
AssertionError

**Comment by mjq11302010044** [comment]
@ljcljc Hi, it seems that you have altered the inference code for your settings?

**Comment by ljcljc** [comment]
Hi, thanks for the reply. I did not change the inference code, I tried to change library code because it will report error like this.

  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/modeling/backbone/backbone.py", line 7, in <module>
    from maskrcnn_benchmark.modeling.make_layers import conv_with_kaiming_uniform
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/modeling/make_layers.py", line 10, in <module>
    from maskrcnn_benchmark.layers import Conv2d
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/layers/__init__.py", line 8, in <module>
    from .roi_align import ROIAlign
  File "/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/layers/roi_align.py", line 8, in <module>
    from maskrcnn_benchmark import _C
ImportError: cannot import name '_C' from 'maskrcnn_benchmark' (/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/__init__.py)

**Comment by mjq11302010044** [comment]
@ljcljc You can try to comment the line 'from .roi_align import ROIAlign' in '/root/anaconda3/envs/rrpn_pytorch/lib/python3.9/site-packages/RRPN-0.0.0-py3.9-linux-x86_64.egg/maskrcnn_benchmark/layers/init.py' to see if it works, since we don't need the RoIAlign in our networks.
