### ISSUE TITLE
how could i get alphabet file.

### ISSUE THREAD

**Issue by Shualite** [mjq11302010044/RRPN_plusplus#3]
Sorry! I found the file "./data_cache/alphabet_IC13_IC15_Syn800K_pro.txt" isn't there, when I try to train it end-to-end. How could I get it. (I'm not familiar with end-to-end tasks, please help me. Thx.)

**Comment by Shualite** [comment]
when i run 'python tools/train_net.py --config-file=configs/arpn_E2E/e2e_rrpn_R_50_C4_1x_train_AFPN_RT_LERB_Spotter.yaml', I got tips as follows:
`We don't expect you to use default class number...Retry it
Empty alphabet...
Traceback (most recent call last):
  File "tools/train_net.py", line 202, in <module>
    main()
  File "tools/train_net.py", line 195, in main
    model = train(cfg, args.local_rank, args.distributed, args.resume, args.config_file)
  File "tools/train_net.py", line 36, in train
    model.to(device)
  File "/home/tongji/anaconda3/envs/rrpn_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/home/tongji/anaconda3/envs/rrpn_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/tongji/anaconda3/envs/rrpn_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/tongji/anaconda3/envs/rrpn_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/tongji/anaconda3/envs/rrpn_pytorch/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "/home/tongji/anaconda3/envs/rrpn_pytorch/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED`

**Comment by mjq11302010044** [comment]
@Shualite If you have run the data processing, the corresponding alphabet will be saved at the ./data_cache/. Try to find it and replace it to the necessary position.

**Comment by ShaheenPerveen** [comment]
@Shualite How did you get the alphabet file?
I am encountering this error:
```
  File "rrpn_e2e_infer.py", line 99, in <module>
    alphabet = open(cfg.MODEL.ROI_REC_HEAD.ALPHABET).readlines()[0] + '-'
FileNotFoundError: [Errno 2] No such file or directory: './data_cache/alphabet_IC13_IC15_Syn800K_pro.txt'
```
